#!/bin/bash
# Quick Setup Guide - Copy this and run in terminal

echo "🦉 Bluie Artistry - Image Setup Helper"
echo "======================================="
echo ""
echo "Step 1: Create images folder"
mkdir -p public/images
echo "✓ public/images/ created (or already exists)"
echo ""
echo "Step 2: Copy your images to this folder:"
echo "   public/images/"
echo "   ├── owl-mascot.jpg       (Main owl mascot - required!)"
echo "   ├── sketching.jpg        (Portrait sketch)"
echo "   ├── paper-quilling.jpg   (Flower composition)"
echo "   ├── thread-art.jpg       (Moon & star art)"
echo "   ├── paper-crafts.jpg     (OM/Ganesha design)"
echo "   ├── ribbon-bouquets.jpg  (Ribbon flowers)"
echo "   ├── mud-clay.jpg         (Clay artwork)"
echo "   └── painting.jpg         (Painting artwork)"
echo ""
echo "Step 3: Verify images are in place"
ls -la public/images/
echo ""
echo "Step 4: Start development server"
echo "   npm run dev"
echo ""
echo "Step 5: Open http://localhost:5173 in browser"
echo ""
echo "Step 6: When ready to deploy"
echo "   npm run build"
echo "   Then deploy the 'dist/' folder"
echo ""
echo "📖 For more info, see:"
echo "   - README.md"
echo "   - DEPLOYMENT_GUIDE.md"
echo "   - IMAGE_GUIDE.md"
